FROM archlinux/base

RUN pacman -Sy
RUN pacman -S jre11-openjdk --noconfirm

ENV SERVER_IP 192.168.1.7:8080
ENV IP 192.168.1.7
ENV PORT 8080

COPY caclServer/target/*.jar /deployments/app.jar
ENTRYPOINT ["java", "-jar", "deployments/app.jar", $(SERVER_IP), $(IP), $(PORT)]
